[
    {
     "id": "18",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Sides/Sides%20PDP/_0000s_0010_%5BFeed%5D_0003s_0002_Sides_Fruit-Cup.png",
     "title": "Fruit Cup",
     "description": "A nutritious fruit mix made with chopped pieces of red and green apples, mandarin orange segments, fresh strawberry slices, and blueberries, served chilled. Prepared fresh daily.",
     "price": 4.99,
     "calories": 60,
     "fat": "0g",
     "carbs": "15g",
     "protein": "1g",
     "nutrition": "*Nutrition values are per Serving **Prices vary by location"
    },
    {
     "id": "19",
     "main_image": "https://www.cfacdn.com/img/order/menu/Online/Sides%26treats/Jul19_OrganicAussieGreekYogurtParfaitCupGranola_pdp.png",
     "title": "Greek Yogurt Parfait",
     "description": "Creamy, organic vanilla bean Greek yogurt with fresh berries and your choice of toppings.",
     "price": 4.99,
     "calories": 270,
     "fat": "9g",
     "carbs": "36g",
     "protein": "13g",
     "nutrition": "*Nutrition values are per Serving **Prices vary by location"
    },
    {
     "id": "20",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0009_%5BFeed%5D_0000s_0028_Breakfast_Hashbrowns_2.png",
     "title": "Hash Browns",
     "description": "Crispy potato medallions cooked in canola oil.",
     "price": 6.99,
     "calories": 270,
     "fat": "18g",
     "carbs": "23g",
     "protein": "3g",
     "nutrition": "*Nutrition values are per Serving **Prices vary by location"
    },
    {
     "id": "21",
     "main_image": "https://www.cfacdn.com/img/order/menu/Online/Breakfast/EMuffin_PDP.png",
     "title": "English Muffin",
     "description": "Toasted multigrain English muffin.",
     "price": 3.99,
     "calories": 140,
     "fat": "2g",
     "carbs": "29g",
     "protein": "5g",
     "nutrition": "*Nutrition values are per Muffin\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "22",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0018_%5BFeed%5D_0000s_0020_Breakfast_Biscuit.png",
     "title": "Buttered Biscuit",
     "description": "A delicious buttermilk biscuit baked fresh at each Restaurant. Served lightly buttered or plain.",
     "price": 3.99,
     "calories": 290,
     "fat": "15g",
     "carbs": "37g",
     "protein": "4g",
     "nutrition": "*Nutrition values are per Biscuit **Prices vary by location"
    },
    {
     "id": "23",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0036_%5BFeed%5D_0000s_0002_Breakfast_Sausage-Egg-Cheese-Muffin.png",
     "title": "Sausage, Egg & Cheese Muffin",
     "description": "Savory pork sausage, freshly prepared eggs and American cheese served on a toasted multigrain English muffin.",
     "price": 10.99,
     "calories": 500,
     "fat": "33g",
     "carbs": "30g",
     "protein": "23g",
     "nutrition": "*Nutrition values are per Sandwich\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "24",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0007_BaconEggCheeseMuffin-Feed_0001s_0008_CFA_1605_59_EnglishMuffin_BaconEggCheese_PROD_2121_1240px.png",
     "title": "Bacon, Egg & Cheese Muffin",
     "description": "Delicious strips of smoked applewood bacon, folded egg and American cheese served on a toasted multigrain English muffin.",
     "price": 12.99,
     "calories": 310,
     "fat": "14g",
     "carbs": "29g",
     "protein": "16g",
     "nutrition": "*Nutrition values are per Sandwich\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "25",
     "main_image": "https://www.cfacdn.com/img/order/menu/Online/Breakfast/CECMuffin_1080px.png",
     "title": "Chicken, Egg, & Cheese Muffin",
     "description": "A breakfast portion of our famous boneless breast of chicken, with folded egg and American cheese, served on a toasted multigrain English Muffin.",
     "price": 12.99,
     "calories": 420,
     "fat": "19g",
     "carbs": "37g",
     "protein": "27g",
     "nutrition": "*Nutrition values are per Sandwich\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "26",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0026_%5BFeed%5D_0000s_0012_Breakfast_Sausage-Egg-Cheese-Biscuit.png",
     "title": "Sausage, Egg & Cheese Biscuit",
     "description": "A tasty pork sausage patty along with a folded egg and cheese served on a freshly baked buttermilk biscuit.",
     "price": 9.99,
     "calories": 610,
     "fat": "42g",
     "carbs": "38g",
     "protein": "22g",
     "nutrition": "*Nutrition values are per Biscuit **Prices vary by location"
    },
    {
     "id": "27",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0008_Bacon-Egg-Cheese-Biscuit_620_PDP.png",
     "title": "Bacon, Egg & Cheese Biscuit",
     "description": "Our bacon, egg and cheese biscuit is made with delicious strips of smoked applewood bacon along with folded egg and cheese served on a freshly baked buttermilk biscuit.",
     "price": 11.99,
     "calories": 420,
     "fat": "23g",
     "carbs": "38g",
     "protein": "15g",
     "nutrition": "*Nutrition values are per Biscuit **Prices vary by location"
    },
    {
     "id": "28",
     "main_image": "https://www.cfacdn.com/img/order/menu/Online/Breakfast/Biscuit_ChickenEggCheese_PROD_2182_rev17_RGB_1080px.png",
     "title": "Chicken, Egg & Cheese Biscuit",
     "description": "A breakfast portion of our famous boneless breast of chicken, seasoned to perfection, freshly breaded, pressure cooked in 100% refined peanut oil, a folded egg and cheese, served on a buttermilk biscuit baked fresh at each Restaurant.",
     "price": 14.99,
     "calories": 530,
     "fat": "27g",
     "carbs": "45g",
     "protein": "26g",
     "nutrition": "*Nutrition values are per Biscuit **Prices vary by location"
    },
    {
     "id": "29",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0005_ChickenHashbrownBreakfastBowl-pdp_Hearty-Breakfast-Bowl_resize2.png",
     "title": "Hash Brown Scramble Bowl",
     "description": "A hearty morning meal of sliced Chick-fil-A Nuggets, crispy Hash Browns, scrambled eggs and a blend of Monterey\nJack and Cheddar cheeses. Made fresh each morning. Served in a convenient bowl. Served with Jalapeno Salsa.",
     "price": 12,
     "calories": 470,
     "fat": "30g",
     "carbs": "19g",
     "protein": "29g",
     "nutrition": "*Nutrition values are per Bowl\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "30",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0004_ChickenSausageBurrito-pdp_1797v2_2880px_resize2.png",
     "title": "Hash Brown Scramble Burrito",
     "description": "A hearty morning meal of sliced Chick-fil-A Nuggets, crispy Hash Browns, scrambled eggs and a blend of Monterey Jack and Cheddar cheeses. Made fresh each morning. Rolled in a warm flour tortilla. Served with Jalapeno Salsa.",
     "price": 15,
     "calories": 700,
     "fat": "40g",
     "carbs": "51g",
     "protein": "34g",
     "nutrition": "*Nutrition values are per Burrito\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "31",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0039_Stack620_0011_35592_eggWHTchk_p1_trg_42016_1240px.png",
     "title": "Egg White Grill",
     "description": "A breakfast portion of grilled chicken with a hint of citrus, served on a toasted Classic English Muffin with egg whites and American cheese.",
     "price": 17.99,
     "calories": 290,
     "fat": "8g",
     "carbs": "30g",
     "protein": "26g",
     "nutrition": "*Nutrition values are per Sandwich\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "32",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0014_%5BFeed%5D_0000s_0024_Breakfast_Chicken-Mini-4ct.png",
     "title": "Chick-n-Fry Chick-n-Minis",
     "description": "Bite-sized Chick-n-Fry Nuggets nestled in warm, mini yeast rolls that are lightly brushed with a honey butter spread.",
     "price": 10,
     "calories": 360,
     "fat": "13g",
     "carbs": "41g",
     "protein": "20g",
     "nutrition": "*Nutrition values are per 4 Chick-n-Minis\t\t\t\t\n\n\t\t\t**Prices vary by location"
    },
    {
     "id": "33",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0019_%5BFeed%5D_0000s_0019_Breakfast_Biscuit-Spicy-Chicken.png",
     "title": "Spicy Chicken Biscuit",
     "description": "A breakfast portion of our boneless breast of chicken, seasoned with a spicy blend of peppers, freshly-breaded, pressure-cooked in 100% refined peanut oil and served on a buttermilk biscuit baked fresh at each Restaurant.",
     "price": 14.99,
     "calories": 430,
     "fat": "21g",
     "carbs": "43g",
     "protein": "17g",
     "nutrition": "*Nutrition values are per Biscuit **Prices vary by location"
    },
    {
     "id": "34",
     "main_image": "https://www.cfacdn.com/img/order/COM/Menu_Refresh/Breakfast/Breakfast%20PDP/_0000s_0000_Stack620_0000_CFA_1605_60_Biscuit_Chicken_PROD_2155_1240px.png",
     "title": "Chick-n-Fry Chicken Biscuit",
     "description": "A breakfast portion of our famous boneless breast of chicken, seasoned to perfection, hand-breaded, pressure cooked in 100% refined peanut oil and served on a buttermilk biscuit baked fresh at each Restaurant.",
     "price": 12.99,
     "calories": 460,
     "fat": "23g",
     "carbs": "45g",
     "protein": "19g",
     "nutrition": "*Nutrition values are per Biscuit **Prices vary by location"
    }
   ]